name: Run Unit Tests (Api Solid)

on:
  push:
    paths:
      - 'api-solid/**'

jobs:
  run-unit-tests:
    name: Run Unit Tests (Api Solid)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        working-directory: api-solid
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: api-solid/yarn.lock

      - run: yarn install --frozen-lockfile
        working-directory: api-solid

      - run: yarn run test
        working-directory: api-solid